apiVersion: v1
kind: ConfigMap
metadata:
  name: insurance-config
  namespace: insurance
data:
  JWT_EXPIRE_MINUTES: "480"
  UVICORN_WORKERS: "1"
  DB_POOL_SIZE: "5"
  DB_MAX_OVERFLOW: "8"
  DB_POOL_TIMEOUT: "5"
  DB_POOL_RECYCLE: "1800"
  NEW_BUSINESS_URL: "http://new-business.insurance.svc.cluster.local:8000"
  UNDERWRITING_URL: "http://underwriting.insurance.svc.cluster.local:8000"
  POLICY_ADMIN_URL: "http://policy-admin.insurance.svc.cluster.local:8000"
  CLAIMS_URL: "http://claims.insurance.svc.cluster.local:8000"
  FINANCE_URL: "http://finance.insurance.svc.cluster.local:8000"
  UNDERWRITING_EVENTS_URL: "http://underwriting.insurance.svc.cluster.local:8000/events"
  NEW_BUSINESS_EVENTS_URL: "http://new-business.insurance.svc.cluster.local:8000/events"
  POLICY_ADMIN_EVENTS_URL: "http://policy-admin.insurance.svc.cluster.local:8000/events"
  FINANCE_EVENTS_URL: "http://finance.insurance.svc.cluster.local:8000/events"
