apiVersion: v1
kind: ConfigMap
metadata:
  name: insurance-config
  namespace: insurance
data:
  JWT_EXPIRE_MINUTES: "480"
  UVICORN_WORKERS: "1"
  DB_POOL_SIZE: "5"
  DB_MAX_OVERFLOW: "8"
  DB_POOL_TIMEOUT: "5"
  DB_POOL_RECYCLE: "1800"
  KAFKA_BOOTSTRAP_SERVERS: "insurance-kafka.insurance.svc.cluster.local:9092"
  KAFKA_DOMAIN_EVENTS_TOPIC: "insurance.domain.events"
  KAFKA_DOMAIN_EVENTS_DLQ_TOPIC: "insurance.domain.events.dlq"
  KAFKA_HANDLER_MAX_RETRIES: "15"
  NEW_BUSINESS_URL: "http://new-business.insurance.svc.cluster.local:8000"
  UNDERWRITING_URL: "http://underwriting.insurance.svc.cluster.local:8000"
  POLICY_ADMIN_URL: "http://policy-admin.insurance.svc.cluster.local:8000"
  CLAIMS_URL: "http://claims.insurance.svc.cluster.local:8000"
  FINANCE_URL: "http://finance.insurance.svc.cluster.local:8000"
